# Generated by Django 5.0.1 on 2024-01-16 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.IntegerField()),
                ('materia', models.TextField()),
                ('texto_questao', models.TextField()),
                ('opcao_a', models.TextField()),
                ('opcao_b', models.TextField()),
                ('opcao_c', models.TextField()),
                ('opcao_d', models.TextField()),
                ('opcao_e', models.TextField()),
                ('correta', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.TextField()),
                ('questoes', models.ManyToManyField(to='app.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha', models.CharField(max_length=1)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidato')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prova')),
            ],
        ),
    ]
