# Generated by Django 5.0.1 on 2024-01-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='correta',
            field=models.CharField(choices=[('A', 'Opção A'), ('B', 'Opção B'), ('C', 'Opção C'), ('D', 'Opção D'), ('E', 'Opção E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')]),
        ),
    ]
