# Generated by Django 5.0.1 on 2024-01-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_prova_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='peso',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prova',
            name='titulo',
            field=models.TextField(null=True),
        ),
    ]
