# Generated by Django 5.0.1 on 2024-01-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_questao_peso_alter_prova_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='titulo',
            field=models.TextField(null=True),
        ),
    ]
