# Generated by Django 5.0.1 on 2024-01-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_questao_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='titulo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questao',
            name='peso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questao',
            name='titulo',
            field=models.TextField(),
        ),
    ]
