# Generated by Django 5.0.1 on 2024-01-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_questao_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='peso',
            field=models.IntegerField(choices=[('1', 'Peso 1'), ('2', 'Peso 2'), ('3', 'Peso 3')]),
        ),
    ]
