# Generated by Django 5.0.1 on 2024-01-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_questao_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
