# Generated by Django 5.0.1 on 2024-01-19 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_prova_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='prova',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.prova'),
        ),
    ]
