# Generated by Django 5.0.1 on 2024-01-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_candidato_prova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='prova',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='escolha',
        ),
        migrations.AddField(
            model_name='resposta',
            name='respostas',
            field=models.TextField(null=True),
        ),
    ]
