# Generated by Django 5.0.1 on 2024-01-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_candidato_prova_remove_resposta_escolha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='respostas',
            field=models.TextField(),
        ),
    ]
